# Generated by Django 4.0.4 on 2022-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ManyToManyField(to='main_app.meal'),
        ),
    ]
