# Generated by Django 4.0.4 on 2022-05-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_goals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='calories',
            field=models.FloatField(default=1),
        ),
    ]
